### ISSUE TITLE
Ajouter les composants suivants dans le cadre de la refonte de numerique.gouv.fr

### ISSUE THREAD

**Issue by Ash-Crow** [numerique-gouv/sites-faciles#100]
Voir aussi la tâche équivalente pour django-dsfr: https://github.com/numerique-gouv/django-dsfr/issues/127

- [x] Badge (#101)
- [x] Carte (#118)
- [x] Citation (#136)
- [x] Contenu média (#136)
- [x] Header (#109)
- [x] Fil d'ariane (#136)
- [x] Lettre d'information et Réseaux Sociaux (#109)
- [x] Lien (#139)
- [x] Menu latéral (#195)
- [x] Mise en avant (#147)
- [x] Mises en exergue (#147)
- [x] Navigation principale
- [ ] Onglets (#206)
- [ ] Partage (#206)
- [x] Tag (#101)
- [x] Téléchargement de fichier : carte de téléchargement + lien de téléchargement (#139)
- [x] Transcription (#136)

À créer même si manquant dans la liste : 
- [x] Tuile (#142)

Ne sera pas géré dans le cadre de cette carte :
- Gestionnaire de consentement → #138
- Champ de saisie  (pour les inscriptions notamment) → #64
